const express = require("express");
const addProduct = require("../controller/addProduct");
const getAllOrders = require("../controller/getAllOrders");
const getUserOrder = require("../controller/getUserOrder");
const paidOrder = require("../controller/paidOrder");
const markAvailable = require("../controller/markAvailable");
const PayByOrderId = require("../controller/PayByOrderId");
const getClientOrder = require("../controller/getClientOrder");
const getManagerOrders = require("../controller/getManagerOrders");
const bulkOrder = require("../controller/bulkOrder");
const getInvoiceOrder = require("../controller/getInvoiceOrder");
const router = express.Router();
router.post("/bulkorder", bulkOrder);
router.post("/payorder");
router.post("/:enrollment", addProduct);
router.post("/paidOrder/:enrollment", paidOrder);
router.get("/getallorders", getAllOrders);
router.get("/getorders/:id", getUserOrder);
router.put("/markavailable/:id", markAvailable);
router.post("/pay/:amount", PayByOrderId);
router.get("/getclientorders/:id", getClientOrder);
router.get("/getmanagerorders/:name", getManagerOrders);
router.get("/getorderforinvoice/:orderId", getInvoiceOrder);
module.exports = router;
