const express = require("express");
const addProduct = require("../controller/addProduct");
const getAllOrders = require("../controller/getAllOrders");
const getUserOrder = require("../controller/getUserOrder");
const paidOrder = require("../controller/paidOrder");
const markAvailable = require("../controller/markAvailable");
const PayByOrderId = require("../controller/PayByOrderId");
const getClientOrder = require("../controller/getClientOrder");
const getManagerOrders = require("../controller/getManagerOrders");
const bulkOrder = require("../controller/bulkOrder");
const getInvoiceOrder = require("../controller/getInvoiceOrder");
const deleteOrder = require("../controller/deleteOrder");
const editOrder = require("../controller/editOrder");
const archiveOrder = require("../controller/archiveOrder");
const getAllArchiveOrders = require("../controller/getAllArchiveOrders");
const shippedOrder = require("../controller/shippedOrder");
const getAllShippedOrder = require("../controller/getAllShippedOrder");
const getManagerBulkOrder = require("../controller/getManagerBulkOrder");
const updateBulk = require("../controller/updateBulk");
const bulkDelete = require("../controller/bulkDelete");
const getUserBulkOrder = require("../controller/getUserBulkOrder");
const getAllBulkOrder = require("../controller/getAllBulkOrder");
const payBulkOrder = require("../controller/payBulkOrder");
const getOrderByDate = require("../controller/getOrderByDate");
const getAllTransaction = require("../controller/getAllTransaction");
const UnarchiveOrder = require("../controller/UnarchiveOrder");
const markUnshipped = require("../controller/markUnshipped");
const getBulkOrderDetails = require("../controller/getBulkOrderDetails");
const addSkuToBulk = require("../controller/addSkuToBulk");
const updateBoxLabel = require("../controller/updateBoxLabel");
const updateFnsku = require("../controller/updateFnsku");
const updatePickupDate = require("../controller/updatePickupDate");
const updateBulkOrder = require("../controller/updateBulkOrder");
const shippedBulkOrder = require("../controller/shippedBulkOrder");
const getAllAccountantOrder = require("../controller/getAllAccountantOrder");
const getOrderByTrackingId = require("../controller/getOrderByTrackingId");
const router = express.Router();
router.get("/getbulkorder/:manager", getManagerBulkOrder);
router.put("/bulkupdate/:id", updateBulk);
router.delete("/bulkdelete/:id", bulkDelete);
router.get("/getuserbulk/:user", getUserBulkOrder);
router.get("/getallbulk", getAllBulkOrder);
router.post("/bulkorder/pay", payBulkOrder);
router.get("/getOrdersByDate", getOrderByDate);
router.get("/alltransactions", getAllTransaction);
router.get("/transactions", getAllTransaction);
router.get("/by-tracking/:trackingId", getOrderByTrackingId);
router.post("/orderAction", UnarchiveOrder);
router.get("/getallorders", getAllOrders);
router.get("/getallaccountantorders", getAllAccountantOrder);
router.post("/unshipped", markUnshipped);
router.post("/bulkorder", bulkOrder);
router.post("/:orderId/addSku", addSkuToBulk);
router.post("/update-box-label", updateBoxLabel);
router.post("/update-fnsku", updateFnsku);
router.post("/update-pickup-date", updatePickupDate);
router.post("/updatebulkorderdetails", updateBulkOrder);
router.post("/shippedbulkorder", shippedBulkOrder);
router.get("/getallshippedorder", getAllShippedOrder);
router.post("/payorder");
router.post("/:enrollment", addProduct);
router.post("/paidOrder/:enrollment", paidOrder);
router.get("/getorders/:id", getUserOrder);
router.put("/markavailable/:id", markAvailable);
router.post("/pay/:amount", PayByOrderId);
router.get("/getclientorders/:id", getClientOrder);
router.get("/getmanagerorders/:name", getManagerOrders);
router.get("/getorderforinvoice/:orderId", getInvoiceOrder);
router.put("/update/:selectedOrderId", editOrder);
router.delete("/delete/:orderId", deleteOrder);
router.put("/archive/:orderId", archiveOrder);
router.put("/shipped/:orderId", shippedOrder);
router.get("/getallarchiveorders", getAllArchiveOrders);
router.get("/:id", getBulkOrderDetails);
module.exports = router;
