const express = require("express");
const router = express.Router();
const createUser = require("../controller/createUser");
const getUserById = require("../controller/getUserById");
const getAllUser = require("../controller/getAllUser");
const getSpecificUserData = require("../controller/getSpecificUserData");
const getManagerClient = require("../controller/getManagerClient");
const getAllManagerUser = require("../controller/getAllManagerUser");
const getAllClients = require("../controller/getAllClients");
const getAllManager = require("../controller/getAllManager");
const payOrder = require("../controller/payOrder");
const createManager = require("../controller/createManager");
const assignManager = require("../controller/assignManager");
const getManagerData = require("../controller/getManagerData");
const updateUserGms = require("../controller/updateUserGms");
const getClientOfManager = require("../controller/getClientOfManager");
const updateGst = require("../controller/updateGst");
const updateClient = require("../controller/updateClient");
const deleteUser = require("../controller/deleteUser");
const sendFromSecond = require("../controller/sendFromSecond");
const getUserBulkOrder = require("../controller/getUserBulkOrder");
const findUserWithEnrollment = require("../controller/findUserWithEnrollment");
router.get("/getallusers", getAllUser);
router.post("/sendfromsecond", sendFromSecond);
router.post("/getBulkOrders",getUserBulkOrder);
router.post("/payorder", payOrder);
router.get("/getallmanagers", getAllManager);
router.get("/find/:enrollment", findUserWithEnrollment);
router.get("/getalluserss", getAllUser);
router.put("/updategms/:id", updateUserGms);
router.get("/getallmanageruserss/:manager", getAllManagerUser);
router.get("/getManagerData/:manager", getManagerData);
router.get("/getallclients", getAllClients);
router.get("/getmanagerclient/:name", getManagerClient);
router.get("/:id", getUserById);
router.get("/specific/:enrollment", getSpecificUserData);
router.post("/register", createUser);
router.post("/registermanager", createManager);
router.post("/assign-manager", assignManager);
router.post("/getmanagerclients", getClientOfManager);
router.post("/add-gst/:enrollment", updateGst);
router.put("/update-client/:id", updateClient);
router.put("/update/:id", updateClient);
router.delete("/delete/:clientId",deleteUser);

module.exports = router;
